// A seeded, editable global Top-100 prospect board, reconstructed from MLB
// Pipeline's 2026 coverage. This is a best-effort starting point (ranks and
// the depth of the list are meant to be reconciled against an authoritative
// source); each entry is enriched with live stats at request time.

export interface Top100Seed {
  rank: number;
  name: string;
  position: string;
  /** Team slug from src/lib/teams.ts. */
  team: string;
  eta?: string;
}

export const TOP100_SEED: Top100Seed[] = [
  { rank: 1, name: 'Konnor Griffin', position: 'SS', team: 'pirates', eta: '2027' },
  { rank: 2, name: 'Kevin McGonigle', position: 'SS', team: 'tigers', eta: '2026' },
  { rank: 3, name: 'Jesus Made', position: 'SS', team: 'brewers', eta: '2028' },
  { rank: 4, name: 'Leo De Vries', position: 'SS', team: 'athletics', eta: '2027' },
  { rank: 5, name: 'JJ Wetherholt', position: '2B', team: 'cardinals', eta: '2026' },
  { rank: 6, name: 'Nolan McLean', position: 'RHP', team: 'mets', eta: '2026' },
  { rank: 7, name: 'Seth Hernandez', position: 'RHP', team: 'pirates', eta: '2028' },
  { rank: 8, name: 'Eli Willits', position: 'SS', team: 'nationals', eta: '2028' },
  { rank: 9, name: 'Colt Emerson', position: 'SS', team: 'mariners', eta: '2027' },
  { rank: 10, name: 'Max Clark', position: 'OF', team: 'tigers', eta: '2027' },
  { rank: 11, name: 'Kade Anderson', position: 'LHP', team: 'mariners', eta: '2027' },
  { rank: 12, name: 'Trey Yesavage', position: 'RHP', team: 'bluejays', eta: '2026' },
  { rank: 13, name: 'Sebastian Walcott', position: 'SS', team: 'rangers', eta: '2026' },
  { rank: 14, name: 'Samuel Basallo', position: 'C', team: 'orioles', eta: '2026' },
  { rank: 15, name: 'Josue De Paula', position: 'OF', team: 'dodgers', eta: '2027' },
  { rank: 16, name: 'Walker Jenkins', position: 'OF', team: 'twins', eta: '2026' },
  { rank: 17, name: 'Thomas White', position: 'LHP', team: 'marlins', eta: '2027' },
  { rank: 18, name: 'Carter Jensen', position: 'C', team: 'royals', eta: '2026' },
  { rank: 19, name: 'Payton Tolle', position: 'LHP', team: 'redsox', eta: '2026' },
  { rank: 20, name: 'Ethan Salas', position: 'C', team: 'padres', eta: '2027' },
  { rank: 21, name: 'Bryce Eldridge', position: '1B', team: 'giants', eta: '2026' },
  { rank: 22, name: 'Braden Montgomery', position: 'OF', team: 'whitesox', eta: '2027' },
  { rank: 23, name: 'Franklin Arias', position: 'SS', team: 'redsox', eta: '2028' },
  { rank: 24, name: 'Travis Bazzana', position: '2B', team: 'guardians', eta: '2026' },
  { rank: 25, name: 'Charlie Condon', position: 'OF', team: 'rockies', eta: '2027' },
  { rank: 26, name: 'Chase Burns', position: 'RHP', team: 'reds', eta: '2026' },
  { rank: 27, name: 'Jac Caglianone', position: '1B', team: 'royals', eta: '2026' },
  { rank: 28, name: 'Owen Caissie', position: 'OF', team: 'cubs', eta: '2026' },
  { rank: 29, name: 'Andrew Painter', position: 'RHP', team: 'phillies', eta: '2026' },
  { rank: 30, name: 'Bubba Chandler', position: 'RHP', team: 'pirates', eta: '2026' },
  { rank: 31, name: 'Aidan Miller', position: 'SS', team: 'phillies', eta: '2027' },
  { rank: 32, name: 'Cam Caminiti', position: 'LHP', team: 'braves', eta: '2028' },
  { rank: 33, name: 'Zyhir Hope', position: 'OF', team: 'dodgers', eta: '2028' },
  { rank: 34, name: 'JR Ritchie', position: 'RHP', team: 'braves', eta: '2026' },
  { rank: 35, name: 'Eduardo Quintero', position: 'OF', team: 'dodgers', eta: '2028' },
  { rank: 36, name: 'Emil Morales', position: 'SS', team: 'dodgers', eta: '2029' },
  { rank: 37, name: 'Tink Hence', position: 'RHP', team: 'cardinals', eta: '2026' },
  { rank: 38, name: 'Jett Williams', position: 'SS', team: 'mets', eta: '2026' },
  { rank: 39, name: 'George Lombard Jr.', position: 'SS', team: 'yankees', eta: '2027' },
  { rank: 40, name: 'Bryce Rainer', position: 'SS', team: 'tigers', eta: '2028' },
  { rank: 41, name: 'Jordan Lawlar', position: 'SS', team: 'diamondbacks', eta: '2026' },
  { rank: 42, name: 'Carson Williams', position: 'SS', team: 'rays', eta: '2026' },
  { rank: 43, name: 'Justin Crawford', position: 'OF', team: 'phillies', eta: '2026' },
  { rank: 44, name: 'Lazaro Montes', position: 'OF', team: 'mariners', eta: '2027' },
  { rank: 45, name: 'Chase DeLauter', position: 'OF', team: 'guardians', eta: '2026' },
  { rank: 46, name: 'Brandon Sproat', position: 'RHP', team: 'mets', eta: '2026' },
  { rank: 47, name: 'Moises Ballesteros', position: 'C', team: 'cubs', eta: '2026' },
  { rank: 48, name: 'Termarr Johnson', position: '2B', team: 'pirates', eta: '2027' },
  { rank: 49, name: 'Cam Collier', position: '3B', team: 'reds', eta: '2027' },
  { rank: 50, name: 'Spencer Jones', position: 'OF', team: 'yankees', eta: '2026' },
  { rank: 51, name: 'Hagen Smith', position: 'LHP', team: 'whitesox', eta: '2026' },
  { rank: 52, name: 'Cooper Pratt', position: 'SS', team: 'brewers', eta: '2027' },
  { rank: 53, name: 'Arjun Nimmala', position: 'SS', team: 'bluejays', eta: '2027' },
  { rank: 54, name: 'Quinn Mathews', position: 'LHP', team: 'cardinals', eta: '2026' },
  { rank: 55, name: 'Starlyn Caba', position: 'SS', team: 'phillies', eta: '2028' },
  { rank: 56, name: 'Carson Benge', position: 'OF', team: 'mets', eta: '2027' },
  { rank: 57, name: 'Josue Briceno', position: 'C', team: 'tigers', eta: '2027' },
  { rank: 58, name: 'Travis Sykora', position: 'RHP', team: 'nationals', eta: '2027' },
  { rank: 59, name: 'Xavier Isaac', position: '1B', team: 'rays', eta: '2027' },
  { rank: 60, name: 'Ethan Holliday', position: 'SS', team: 'rockies', eta: '2028' },
  { rank: 61, name: 'Billy Carlson', position: 'SS', team: 'whitesox', eta: '2028' },
  { rank: 62, name: 'Aiva Arquette', position: 'SS', team: 'mariners', eta: '2028' },
  { rank: 63, name: 'Liam Doyle', position: 'LHP', team: 'cardinals', eta: '2027' },
  { rank: 64, name: 'JoJo Parker', position: 'SS', team: 'bluejays', eta: '2028' },
  { rank: 65, name: 'Felnin Celesten', position: 'SS', team: 'mariners', eta: '2028' },
  { rank: 66, name: 'Gavin Kilen', position: '2B', team: 'brewers', eta: '2027' },
  { rank: 67, name: 'Welbyn Francisca', position: 'SS', team: 'guardians', eta: '2028' },
  { rank: 68, name: 'Dakota Jordan', position: 'OF', team: 'giants', eta: '2027' },
  { rank: 69, name: 'Kevin Alcantara', position: 'OF', team: 'cubs', eta: '2026' },
  { rank: 70, name: 'Roderick Arias', position: 'SS', team: 'yankees', eta: '2027' },
  { rank: 71, name: 'Christian Moore', position: '2B', team: 'angels', eta: '2026' },
  { rank: 72, name: 'Nelson Rada', position: 'OF', team: 'angels', eta: '2027' },
  { rank: 73, name: 'Jefferson Rojas', position: 'SS', team: 'cubs', eta: '2027' },
  { rank: 74, name: 'Jaison Chourio', position: 'OF', team: 'guardians', eta: '2027' },
  { rank: 75, name: 'Angel Genao', position: 'SS', team: 'guardians', eta: '2027' },
  { rank: 76, name: 'Sal Stewart', position: '3B', team: 'reds', eta: '2026' },
  { rank: 77, name: 'Enrique Bradfield Jr.', position: 'OF', team: 'orioles', eta: '2026' },
  { rank: 78, name: 'Vance Honeycutt', position: 'OF', team: 'orioles', eta: '2027' },
  { rank: 79, name: 'Emmanuel Rodriguez', position: 'OF', team: 'twins', eta: '2026' },
  { rank: 80, name: 'Kaelen Culpepper', position: 'SS', team: 'twins', eta: '2027' },
  { rank: 81, name: 'Slade Caldwell', position: 'OF', team: 'diamondbacks', eta: '2028' },
  { rank: 82, name: 'Druw Jones', position: 'OF', team: 'diamondbacks', eta: '2027' },
  { rank: 83, name: 'Caleb Bonemer', position: 'SS', team: 'angels', eta: '2028' },
  { rank: 84, name: 'Eric Bitonti', position: '3B', team: 'brewers', eta: '2028' },
  { rank: 85, name: 'Carson Whisenhunt', position: 'LHP', team: 'giants', eta: '2026' },
  { rank: 86, name: 'Rayner Arias', position: 'OF', team: 'giants', eta: '2028' },
  { rank: 87, name: 'Robby Snelling', position: 'LHP', team: 'marlins', eta: '2026' },
  { rank: 88, name: 'Brody Hopkins', position: 'RHP', team: 'rays', eta: '2027' },
  { rank: 89, name: 'Gavin Fien', position: '3B', team: 'rangers', eta: '2028' },
  { rank: 90, name: 'Alejandro Rosario', position: 'RHP', team: 'rangers', eta: '2026' },
  { rank: 91, name: 'Cole Carrigg', position: 'OF', team: 'rockies', eta: '2027' },
  { rank: 92, name: 'Alfredo Duno', position: 'C', team: 'reds', eta: '2028' },
  { rank: 93, name: 'Brock Wilken', position: '3B', team: 'brewers', eta: '2026' },
  { rank: 94, name: 'Tommy White', position: '3B', team: 'athletics', eta: '2026' },
  { rank: 95, name: 'Luis Morales', position: 'RHP', team: 'athletics', eta: '2026' },
  { rank: 96, name: 'Michael Arroyo', position: '2B', team: 'mariners', eta: '2027' },
  { rank: 97, name: 'Jhostynxon Garcia', position: 'OF', team: 'redsox', eta: '2027' },
  { rank: 98, name: 'Caden Dana', position: 'RHP', team: 'angels', eta: '2026' },
  { rank: 99, name: 'Payton Martin', position: 'RHP', team: 'dodgers', eta: '2027' },
  { rank: 100, name: 'Welinton Herrera', position: 'LHP', team: 'cubs', eta: '2028' },
];
